stages:
  - setup
  - code_formating
  - test_client

variables:
  CLIENT_DIR: 'client'
  BACKEND_DIR: 'server'

setup-backend:
  stage: setup
  image: node:alpine
  script:
    - cd $BACKEND_DIR
    - npm ci
  artifacts:
    paths:
      - $BACKEND_DIR/node_modules
    when: on_success
    expire_in: 1 hour

setup-frontend:
  stage: setup
  image: node:alpine
  script:
    - cd $CLIENT_DIR
    - npm ci
  artifacts:
    paths:
      -  $CLIENT_DIR/node_modules
    when: on_success
    expire_in: 1 hour

lint_backend:
    stage: code_formating
    image: node:alpine
    script:
      - cd $BACKEND_DIR
      - npm run lint

format_backend:
    stage: code_formating
    image: node:alpine
    script:
      - cd $BACKEND_DIR
      - npm run format

lint_client:
    stage: code_formating
    image: node:alpine
    script:
      - cd $BACKEND_DIR
      - npm run lint

format_client:
    stage: code_formating
    image: node:alpine
    script:
      - cd $CLIENT_DIR
      - npm run format

test_client:
  stage: test_client
  image: node:alpine
  before_script:
    - cd $CLIENT_DIR
  script:
    - npm run test