stages:
  - setup
  -  lint
  - test

variables:
  CLIENT_DIR: 'client'
  BACKEND_DIR: 'server'

setup-backend:
  stage: setup
  image: node:alpine
  script:
    - cd $BACKEND_DIR
    - npm ci
  artifacts:
    paths:
      - $BACKEND_DIR/node_modules
    when: on_success
    expire_in: 1 hour

setup-frontend:
  stage: setup
  image: node:alpine
  script:
    - cd $CLIENT_DIR
    - npm ci
  artifacts:
    paths:
      -  $CLIENT_DIR/node_modules
    when: on_success
    expire_in: 1 hour

lint:
    stage: lint
    image: node:alpine
    script:
      - npm run lint

backend-unit-tests:
  stage: test
  image: node:alpine
  before_script:
    - cd $BACKEND_DIR
  script:
    - npm run test