stages:
  - setup
  - test

variables:
  CLIENT_DIR: 'client'
  BACKEND_DIR: 'server'

cache:
  paths:
    - ./$CLIENT_DIR/node_modules
    - ./$BACKEND_DIR/node_modules

setup-backend:
  stage: setup
  image: node:alpine
  script:
    - cd $BACKEND_DIR
    - npm ci
  cache:
    key: server
    paths:
      - node_modules/

setup-frontend:
  stage: setup
  image: node:alpine
  script:
    - cd $CLIENT_DIR
    - npm ci
  cache:
    key: client
    paths:
      - node_modules/

unit-tests:
  stage: test
  image: node:alpine
  before_script:
    - cd $CLIENT_DIR
  script:
    - npm run test

e2e-tests:
  stage: test
  image: node:alpine
  before_script:
    - cd $BACKEND_DIR
  script:
    - npm run test:e2e