stages:
  - setup
  - test

variables:
  CLIENT_DIR: 'client'
  BACKEND_DIR: 'server'

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ./$CLIENT_DIR/.npm
    - ./$BACKEND_DIR/.npm

setup-backend:
  stage: setup
  image: node:alpine
  script:
    - cd $BACKEND_DIR
    - npm ci --cache .npm --prefer-offline

setup-frontend:
  stage: setup
  image: node:alpine
  script:
    - cd $CLIENT_DIR
    - npm ci
  cache:
    key: client
    paths:
      - node_modules/

backend-unit-tests:
  stage: test
  image: node:alpine
  before_script:
    - cd $BACKEND_DIR
  script:
    - npm list
    - npm run test