version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env.production
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/myDatabase
    depends_on:
      - ecoscan-db
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env.production
    networks:
      - app-network

  ecoscan-db:
    image: mongo:4.4
    container_name: ecoscan-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
