version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env.production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000", "||", "exit", "1"]
      interval: 5s
      retries: 3
      timeout: 3s

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://ecoscan-db:27017/myDatabase
    depends_on:
      - ecoscan-db
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env.production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3001", "||", "exit", "1"]
      interval: 5s
      retries: 3
      timeout: 3s

  ecoscan-db:
    image: mongo:4.4
    container_name: ecoscan-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
